# Generated by Django 3.0.5 on 2020-04-22 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=80)),
                ('neighborhood', models.CharField(max_length=80)),
                ('street', models.CharField(max_length=80)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
    ]
