# Generated by Django 3.0.5 on 2020-04-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0004_auto_20200422_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
