# Generated by Django 3.0.5 on 2020-05-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_auto_20200422_0501'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='address',
            table='addresses',
        ),
    ]
