# Generated by Django 3.0.5 on 2020-05-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesshours', '0002_auto_20200422_0148'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='businesshours',
            table='business_hours',
        ),
    ]
