# Generated by Django 3.0.5 on 2020-04-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_hours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('minimum_age', models.PositiveSmallIntegerField()),
                ('business_days', models.ManyToManyField(to='business_hours.BusinessHours')),
            ],
        ),
    ]
