# Generated by Django 3.0.5 on 2020-05-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attraction',
            table='attractions',
        ),
    ]
