# Generated by Django 3.0.5 on 2020-04-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('touristattractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristattraction',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
