# Generated by Django 3.0.5 on 2020-04-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('touristattractions', '0003_touristattraction_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='assessments',
            field=models.ManyToManyField(to='assessments.Assessment'),
        ),
    ]
