# Generated by Django 3.0.5 on 2020-04-22 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business_hours', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business_hours',
            options={'verbose_name_plural': 'Business Hours'},
        ),
    ]
