# Generated by Django 3.0.5 on 2020-04-22 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0005_auto_20200422_0501'),
        ('tourist_attractions', '0004_touristattraction_assessments'),
    ]

    operations = [
        migrations.AddField(
            model_name='touristattraction',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addresses.Address'),
        ),
    ]
