# Generated by Django 3.0.5 on 2020-05-04 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourist_attractions', '0005_touristattraction_address'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='touristattraction',
            table='tourist_attractions',
        ),
    ]
